### ISSUE TITLE
problem with your code in adding a new page 

### ISSUE THREAD

**Issue by techsaqib** [chanakaDe/Mint-REST#4]
Hi , its really a great project for start but i am facing a problem in adding a new page 

i want user go to /dashbored after login but that page is not secure now 

i can easly go to that page 

localhost:3000/dahsbored

how i add this to after login page but not by direct thanks 

i add api.post('/dashbored'); after  the code where you checking every token ? 

Please help 

and i also not able to understand this 

api.get('/me', function (req, res) {
        res.json(req.decoded);
        console.log(req.decoded);
    });

what it do ?

**Comment by chanakaDe** [comment]
Hai,
Thanks for your interest. Basically this is a REST API and this serves JSON documents as output. If you want to add support to use inbuilt HTML pages , you have to configure the API from the scratch. So it's better to use another directory as a web front end. I also have created a front end for this REST API. Please check it. This is it. https://github.com/chanakaDe/Mint-Blog/tree/development

You can see all the codes. Implemented in AngularJS.
Please feel free to ask anything.
I am still developing this REST API.
